name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compiler tets.c
        run: gcc tets.c -o programme
      - name: Executer le programme
        run: ./programme
      